data:
  table: "raw_data"
  data_path: "data/game.csv"
  features_columns:
    - "season_id"

model:
  model_name: "model_1"
  model_type: "classification"
  model_params:
    max_iter: 100
    random_state: 42
